const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.AddVar,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event8,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{Fundo: 0},
	{Lua: 0},
	{Sólido: 0},
	{Chão1: 0},
	{Chão2: 0},
	{Chão3: 0},
	{Vida: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{Vampiro: 0},
	{Chão4: 0},
	{Keyboard: 0},
	{Solid: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{alho: 0},
	{txt_vidas: 0},
	{Sprite5: 0},
	{btn_restart: 0},
	{imginicial: 0},
	{btn_inicial: 0},
	{blood: 0},
	{Text: 0},
	{imgfinal: 0},
	{btn_final: 0},
	{Audio: 0},
	{Sprite6: 0},
	{arvore: 0},
	{arvoremenor: 0},
	{Sprite7: 0},
	{caixa: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{G_Vida: 0},
	{G_Sangue: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Fundo: class extends self.ITiledBackgroundInstance {},
	Lua: class extends self.ISpriteInstance {},
	Chão1: class extends self.ISpriteInstance {},
	Chão2: class extends self.ISpriteInstance {},
	Chão3: class extends self.ISpriteInstance {},
	Vampiro: class extends self.ISpriteInstance {},
	Chão4: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	alho: class extends self.ISpriteInstance {},
	txt_vidas: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	btn_restart: class extends self.IButtonInstance {},
	imginicial: class extends self.ISpriteInstance {},
	btn_inicial: class extends self.IButtonInstance {},
	blood: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	imgfinal: class extends self.ISpriteInstance {},
	btn_final: class extends self.IButtonInstance {},
	Audio: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	arvore: class extends self.ISpriteInstance {},
	arvoremenor: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {}
}